trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '7b745d95-f8ed-4c9a-ae02-d482d03a52eb'
  imageRepository: 'danielkeaneweb'
  containerRegistry: 'danielkeane.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:

- stage: Build
  displayName: Build WAR file using Gradle
  jobs:  
  - job: GradleDocker
    displayName: Gradle Build & Docker Build & Docker Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Daniel Keane(4cb156f3-eaa3-4189-bc1d-71fc08366930)'
        appType: 'webAppContainer'
        WebAppName: 'danielkeane'
        DockerNamespace: $(containerRegistry)
        DockerRepository: $(imageRepository)
        DockerImageTag: $(tag)